---
- name: Install Google Chrome on Windows systems
  gather_facts: false
  become: false
  hosts: servers
  vars_files: vars.yml
  tasks:
    - name: Download Chrome from S3
      aws_s3:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        bucket: bucket_name
        object: googlechromestandaloneenterprise64.msi
        dest: googlechromestandaloneenterprise64.msi
        mode: get
      delegate_to: localhost

    - name: Check if temp directory exists on remote host
      win_file:
        path: C:\temp
        state: directory

    - name: Upload installer to remote host
      win_copy:
        src: "googlechromestandaloneenterprise64.msi"
        dest: "C:\\temp\\googlechromestandaloneenterprise64.msi"

    - name: Install Chrome
      win_shell: msiexec /i C:\temp\googlechromestandaloneenterprise64.msi /qn /norestart
